#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  teste2
#  
#  Copyright 2022 HDN <HDN@LAPTOP-P3D340I9>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  


#def main(args):
 #  return 0

#if __name__ == '__main__':
    #import sys
  #  print("dhiulia")
    #sys.exit(main(sys.argv))

#a = 3
#b = 4
#print(a + b)

#nome = input("Informe seu nome:")
#print("Seu nome é", nome)

#if nome == "dhiu":
#	print("nome legal")
#elif nome == "mike":
#	print("vc eh um cachorro")
#else:
#	print ("fodase?")

#lojas = {"renner", "c&a", "reggla", "pompeia"}

#for loja in lojas:
#	print(loja)

#nums = {3, 2, 1, 0}
#for i in range(4):
#	print(i)
#	print(nums[i])	

#for letra in "dhiu":
#	print(letra)

#num = 3
#while num > 0:
#	num = int(input("escreva um numero"))
#	print("ok")
letras = {}
for i in range(5):
	letra = input("Informe uma letra:")
	letras[i] = letra

for i in range(5):
   print(letras[i])
   
